# application.yml
server:
  port: 8080
app:
  kafka:
    cluster1:
      bootstrap-servers: 127.0.0.1:9092
      group-id: group1
      security:
        enabled: false
        protocol: SASL_PLAINTEXT
        mechanism: PLAIN
        username: kafkauser
        password: Kedacom#321
    cluster2:
      bootstrap-servers: 127.0.0.1:19092
      group-id: group2
      security:
        enabled: true
        protocol: SASL_PLAINTEXT
        mechanism: PLAIN
        username: kafkauser
        password: Kedacom#321
